name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install deps
        run: sudo apt install -y pv dc3dd

      - name: Shellcheck
        run: shellcheck ./sfsimage

      - name: Download alpine img
        run: curl -OL https://dl-cdn.alpinelinux.org/alpine/v3.19/releases/x86/alpine-virt-3.19.1-x86.iso

      - name: Create archive
        run: sudo ./sfsimage -i ./alpine-virt-3.19.1-x86.iso test.sfs

      - name: List content
        run: ./sfsimage -l ./test.sfs

      - name: Mount archive
        run: sudo ./sfsimage -m ./test.sfs

      - name: Check log is done
        run: test -f ./test.sfs.d/sfsimagelog.txt

      - name: Print log
        run: cat ./test.sfs.d/sfsimagelog.txt
